# GENERATE TIME: Thu Mar 28 01:14:04 2024
# CMD:
# basicsr/train.py --local_rank=0 -opt options/train/ShiftNet/gopro_rvrt_V13.yml --launcher pytorch

# ------------------------------------------------------------------------
# Copyright (c) 2021 megvii-model. All Rights Reserved.
# ------------------------------------------------------------------------
# Modified from BasicSR (https://github.com/xinntao/BasicSR)
# Copyright 2018-2020 BasicSR Authors
# ------------------------------------------------------------------------
# general settings
name: GoPro_debug
model_type: ModelBSST
manual_seed: 0
num_gpu: auto
reload: true
retrain: False
flowrefine_ratio: 0.1
offset_ratio: 0.25
softconv_ratio: 0.5
no_fix_flow: true
network_g:
  type: BSST
datasets:
  train:
    name: VideoDeblur
    type: DeblurRecurrentDataset
    dataroot_gt: ./datasets/GoPro/train/GT
    dataroot_lq: ./datasets/GoPro/train/blur
    meta_info_file: basicsr/data/meta_info/GoPro_train.txt
    val_partition: ~
    test_mode: False
    io_backend:
      type: disk
    file_end: png

    num_frame: 24
    gt_size: 256
    scale: 1
    interval_list: [1]
    random_reverse: false
    use_hflip: True
    use_rot: true
    cache_data: false

    num_worker_per_gpu: 8
    batch_size_per_gpu: 1
    dataset_enlarge_ratio: 1000
    prefetch_mode: ~
    
  val:
    name: gopro
    type: VideoRecurrentTestDatasetlocal
    dataroot_gt: ./datasets/GoPro/test/GT
    dataroot_lq: ./datasets/GoPro/test/blur

    cache_data: false
    io_backend:
      type: disk

    num_frame: 48  
  
path:
  pretrain_network_g: model_zoo/BSST_gopro.pth
  strict_load_g: true
  resume_state: ~

train:
  optim_g:
    type: Adam
    lr: !!float 1e-5
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: TrueCosineAnnealingLR
    T_max: 600000
    eta_min: !!float 1e-7

  total_iter: 600000
  warmup_iter: 1000 # no warm up
  fix_flow: 10000

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1
    reduction: mean

# validation settings
val:
  val_freq: !!float 500
  save_img: false
  crop_size: 256
  max_minibatch: 1

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim:
      type: ssim_calculate

    
# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: 500
  use_tb_logger: true
  wandb:
    # project: "tubedeblur"  
    project: ~
    # resume_id: "1bw5zbkx"
    resume_id: ~
    # wandb_name: "rvrt_basewithraft_V2_8deth_rec"
    wandb_name: ~


# dist training settings
dist_params:
  backend: nccl
  port: 29510
find_unused_parameters: True
